spring:
  datasource:
    url: jdbc:mysql://localhost:3306/salon
    username: root
    password: root
  flyway:
    clean-disabled: false
    baseline-on-migrate: true
server:
    port: 8082
springdoc:
  packages-to-scan:
    - com.salonhub.api

# JWT Configuration
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours in milliseconds