spring:
  datasource:
    url: jdbc:h2:mem:salon_hub_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: false  # Disable Flyway for H2 testing
server:
  port: 8082
springdoc:
  packages-to-scan:
    - com.salonhub.api
